version: '3.8'
services:
  mysql:
    container_name: nestjs-template-mysql
    image: mysql:5.7.27
    restart: always
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=nestjs-template-db
      - TZ=Asia/Seoul
    ports:
      - '3307:3306'
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
    command: 
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
      ]
  redis:
    container_name: nestjs-template-redis
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - ./redis/redis_data:/data
